apiVersion: apps/v1
kind: Deployment
metadata:
  name: note-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: note
  template:
    metadata:
      labels:
        app: note
    spec:
      serviceAccountName: demo-sa
      containers:
        - name: note-container
          image: giles97/k8s-note-app:latest
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: app-config
          volumeMounts:
            - mountPath: "/data"
              name: note-storage
      volumes:
        - name: note-storage
          persistentVolumeClaim:
            claimName: demo-pvc

